// src/main/static/src/overview/VariableBox.jsx
import React from "react";
import './VariableBox.css';

export default function VariableBox({ title, children }) {
  return (
    <div className="variable-box-container">
      <div className="variable-box-title">{title}</div>
      <div className="variable-box-contents">{children}</div>
    </div>
  );
};

export function TextBox({ title, children }) {
  return <VariableBox title={title} className="text-box"><span className="variable-text">{children}</span></VariableBox>;
};

// src/main/static/src/lib/components/VariableBox.svelte
<script>
  import DataBox from "$lib/components/DataBox.svelte";

  let { children, title } = $props();
</script>

<DataBox {title}>
  <div class="variable-box-contents">
    <span class="variable-text text-xl">
      {@render children?.()}
    </span>
  </div>
</DataBox>

<style>
  .variable-box-contents {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .variable-text {
    padding: 12px 24px;
    text-align: center;
    display: block;
  }
</style>
